// Derived from the MathJax / standard LaTeX command set — bundle-scoped
// (MathJax base + ams + newcommand). Symbol commands carry a `glyph`; commands taking
// arguments carry a CM6 snippet `template` (empty ${} fields + a terminal ${} tab-stop).
// Array order is the curated default ranking (frequency boost overrides it at use time).

export interface LatexCommand {
  /** Matched against and shown in the completion list, e.g. `\\varepsilon`, `\\frac`. */
  readonly label: string;
  /** Representative Unicode glyph, shown as completion detail. Absent for structural commands. */
  readonly glyph?: string;
  /** CM6 snippet template for commands that take arguments. Absent → insert `label` verbatim. */
  readonly template?: string;
}

export const LATEX_COMMANDS: readonly LatexCommand[] = [
  { label: "\\alpha", glyph: "α" },
  { label: "\\beta", glyph: "β" },
  { label: "\\gamma", glyph: "γ" },
  { label: "\\delta", glyph: "δ" },
  { label: "\\epsilon", glyph: "ε" },
  { label: "\\varepsilon", glyph: "ε" },
  { label: "\\zeta", glyph: "ζ" },
  { label: "\\eta", glyph: "η" },
  { label: "\\theta", glyph: "θ" },
  { label: "\\vartheta", glyph: "ϑ" },
  { label: "\\iota", glyph: "ι" },
  { label: "\\kappa", glyph: "κ" },
  { label: "\\lambda", glyph: "λ" },
  { label: "\\mu", glyph: "μ" },
  { label: "\\nu", glyph: "ν" },
  { label: "\\xi", glyph: "ξ" },
  { label: "\\pi", glyph: "π" },
  { label: "\\varpi", glyph: "ϖ" },
  { label: "\\rho", glyph: "ρ" },
  { label: "\\varrho", glyph: "ϱ" },
  { label: "\\sigma", glyph: "σ" },
  { label: "\\varsigma", glyph: "ς" },
  { label: "\\tau", glyph: "τ" },
  { label: "\\upsilon", glyph: "υ" },
  { label: "\\phi", glyph: "φ" },
  { label: "\\varphi", glyph: "φ" },
  { label: "\\chi", glyph: "χ" },
  { label: "\\psi", glyph: "ψ" },
  { label: "\\omega", glyph: "ω" },
  { label: "\\Gamma", glyph: "Γ" },
  { label: "\\Delta", glyph: "Δ" },
  { label: "\\Theta", glyph: "Θ" },
  { label: "\\Lambda", glyph: "Λ" },
  { label: "\\Xi", glyph: "Ξ" },
  { label: "\\Pi", glyph: "Π" },
  { label: "\\Sigma", glyph: "Σ" },
  { label: "\\Upsilon", glyph: "Υ" },
  { label: "\\Phi", glyph: "Φ" },
  { label: "\\Psi", glyph: "Ψ" },
  { label: "\\Omega", glyph: "Ω" },
  { label: "\\digamma", glyph: "ϝ" },
  { label: "\\varkappa", glyph: "ϰ" },
  { label: "\\pm", glyph: "±" },
  { label: "\\mp", glyph: "∓" },
  { label: "\\times", glyph: "×" },
  { label: "\\div", glyph: "÷" },
  { label: "\\cdot", glyph: "·" },
  { label: "\\ast", glyph: "∗" },
  { label: "\\star", glyph: "⋆" },
  { label: "\\circ", glyph: "∘" },
  { label: "\\bullet", glyph: "•" },
  { label: "\\cap", glyph: "∩" },
  { label: "\\cup", glyph: "∪" },
  { label: "\\vee", glyph: "∨" },
  { label: "\\wedge", glyph: "∧" },
  { label: "\\oplus", glyph: "⊕" },
  { label: "\\ominus", glyph: "⊖" },
  { label: "\\otimes", glyph: "⊗" },
  { label: "\\odot", glyph: "⊙" },
  { label: "\\oslash", glyph: "⊘" },
  { label: "\\setminus", glyph: "∖" },
  { label: "\\amalg", glyph: "⨿" },
  { label: "\\uplus", glyph: "⊎" },
  { label: "\\sqcap", glyph: "⊓" },
  { label: "\\sqcup", glyph: "⊔" },
  { label: "\\wr", glyph: "≀" },
  { label: "\\dotplus", glyph: "∔" },
  { label: "\\smallsetminus", glyph: "∖" },
  { label: "\\intercal", glyph: "⊺" },
  { label: "\\ltimes", glyph: "⋉" },
  { label: "\\rtimes", glyph: "⋊" },
  { label: "\\divideontimes", glyph: "⋇" },
  { label: "\\veebar", glyph: "⊻" },
  { label: "\\boxtimes", glyph: "⊠" },
  { label: "\\leq", glyph: "≤" },
  { label: "\\geq", glyph: "≥" },
  { label: "\\neq", glyph: "≠" },
  { label: "\\equiv", glyph: "≡" },
  { label: "\\sim", glyph: "∼" },
  { label: "\\simeq", glyph: "≃" },
  { label: "\\approx", glyph: "≈" },
  { label: "\\cong", glyph: "≅" },
  { label: "\\ll", glyph: "≪" },
  { label: "\\gg", glyph: "≫" },
  { label: "\\subset", glyph: "⊂" },
  { label: "\\supset", glyph: "⊃" },
  { label: "\\subseteq", glyph: "⊆" },
  { label: "\\supseteq", glyph: "⊇" },
  { label: "\\in", glyph: "∈" },
  { label: "\\ni", glyph: "∋" },
  { label: "\\notin", glyph: "∉" },
  { label: "\\mid", glyph: "∣" },
  { label: "\\parallel", glyph: "∥" },
  { label: "\\perp", glyph: "⊥" },
  { label: "\\vdash", glyph: "⊢" },
  { label: "\\models", glyph: "⊨" },
  { label: "\\doteq", glyph: "≐" },
  { label: "\\propto", glyph: "∝" },
  { label: "\\prec", glyph: "≺" },
  { label: "\\succ", glyph: "≻" },
  { label: "\\preceq", glyph: "⪯" },
  { label: "\\succeq", glyph: "⪰" },
  { label: "\\asymp", glyph: "≍" },
  { label: "\\smile", glyph: "⌣" },
  { label: "\\frown", glyph: "⌢" },
  { label: "\\leqq", glyph: "≦" },
  { label: "\\geqq", glyph: "≧" },
  { label: "\\leqslant", glyph: "⩽" },
  { label: "\\geqslant", glyph: "⩾" },
  { label: "\\lesssim", glyph: "≲" },
  { label: "\\gtrsim", glyph: "≳" },
  { label: "\\approxeq", glyph: "≊" },
  { label: "\\lessgtr", glyph: "≶" },
  { label: "\\gtrless", glyph: "≷" },
  { label: "\\lesseqgtr", glyph: "⋚" },
  { label: "\\gtreqless", glyph: "⋛" },
  { label: "\\doteqdot", glyph: "≑" },
  { label: "\\triangleq", glyph: "≜" },
  { label: "\\bumpeq", glyph: "≏" },
  { label: "\\preccurlyeq", glyph: "≼" },
  { label: "\\succcurlyeq", glyph: "≽" },
  { label: "\\subseteqq", glyph: "⫅" },
  { label: "\\supseteqq", glyph: "⫆" },
  { label: "\\subsetneq", glyph: "⊊" },
  { label: "\\supsetneq", glyph: "⊋" },
  { label: "\\Subset", glyph: "⋐" },
  { label: "\\Supset", glyph: "⋑" },
  { label: "\\sqsubset", glyph: "⊏" },
  { label: "\\sqsupseteq", glyph: "⊒" },
  { label: "\\sqsubseteq", glyph: "⊑" },
  { label: "\\vartriangleleft", glyph: "⊲" },
  { label: "\\vartriangleright", glyph: "⊳" },
  { label: "\\trianglelefteq", glyph: "⊴" },
  { label: "\\trianglerighteq", glyph: "⊵" },
  { label: "\\Vdash", glyph: "⊩" },
  { label: "\\vDash", glyph: "⊨" },
  { label: "\\nvdash", glyph: "⊬" },
  { label: "\\nvDash", glyph: "⊭" },
  { label: "\\nleq", glyph: "≰" },
  { label: "\\ngeq", glyph: "≱" },
  { label: "\\nleqslant", glyph: "⩽̸" },
  { label: "\\ngeqslant", glyph: "⩾̸" },
  { label: "\\nmid", glyph: "∤" },
  { label: "\\nparallel", glyph: "∦" },
  { label: "\\nsubseteq", glyph: "⊄" },
  { label: "\\nsupseteq", glyph: "⊅" },
  { label: "\\ntriangleleft", glyph: "⋪" },
  { label: "\\ntriangleright", glyph: "⋫" },
  { label: "\\therefore", glyph: "∴" },
  { label: "\\because", glyph: "∵" },
  { label: "\\lvert", glyph: "|" },
  { label: "\\rvert", glyph: "|" },
  { label: "\\lVert", glyph: "‖" },
  { label: "\\rVert", glyph: "‖" },
  { label: "\\leftarrow", glyph: "←" },
  { label: "\\rightarrow", glyph: "→" },
  { label: "\\leftrightarrow", glyph: "↔" },
  { label: "\\Leftarrow", glyph: "⇐" },
  { label: "\\Rightarrow", glyph: "⇒" },
  { label: "\\Leftrightarrow", glyph: "⟺" },
  { label: "\\longleftarrow", glyph: "⟵" },
  { label: "\\longrightarrow", glyph: "⟶" },
  { label: "\\Longleftarrow", glyph: "⟸" },
  { label: "\\Longrightarrow", glyph: "⟹" },
  { label: "\\Longleftrightarrow", glyph: "⟺" },
  { label: "\\iff", glyph: "⟺" },
  { label: "\\mapsto", glyph: "↦" },
  { label: "\\longmapsto", glyph: "⟼" },
  { label: "\\uparrow", glyph: "↑" },
  { label: "\\downarrow", glyph: "↓" },
  { label: "\\Uparrow", glyph: "⇑" },
  { label: "\\Downarrow", glyph: "⇓" },
  { label: "\\nearrow", glyph: "↗" },
  { label: "\\nwarrow", glyph: "↖" },
  { label: "\\swarrow", glyph: "↙" },
  { label: "\\searrow", glyph: "↘" },
  { label: "\\hookleftarrow", glyph: "↩" },
  { label: "\\hookrightarrow", glyph: "↪" },
  { label: "\\leftharpoonup", glyph: "↼" },
  { label: "\\rightharpoonup", glyph: "⇀" },
  { label: "\\rightleftharpoons", glyph: "⇌" },
  { label: "\\xleftarrow", glyph: "←", template: "\\xleftarrow{${}}${}" },
  { label: "\\xrightarrow", glyph: "→", template: "\\xrightarrow{${}}${}" },
  { label: "\\twoheadrightarrow", glyph: "↠" },
  { label: "\\rightsquigarrow", glyph: "↝" },
  { label: "\\dashrightarrow", glyph: "⇢" },
  { label: "\\rightarrowtail", glyph: "↣" },
  { label: "\\curvearrowleft", glyph: "↶" },
  { label: "\\curvearrowright", glyph: "↷" },
  { label: "\\upharpoonright", glyph: "↾" },
  { label: "\\implies", glyph: "⟹" },
  { label: "\\impliedby", glyph: "⟸" },
  { label: "\\nleftarrow", glyph: "↚" },
  { label: "\\nrightarrow", glyph: "↛" },
  { label: "\\sum", glyph: "∑" },
  { label: "\\prod", glyph: "∏" },
  { label: "\\coprod", glyph: "∐" },
  { label: "\\int", glyph: "∫" },
  { label: "\\oint", glyph: "∮" },
  { label: "\\iint", glyph: "∬" },
  { label: "\\iiint", glyph: "∭" },
  { label: "\\iiiint", glyph: "⨌" },
  { label: "\\idotsint", glyph: "∫⋯∫" },
  { label: "\\oiint", glyph: "∯" },
  { label: "\\bigcap", glyph: "⋂" },
  { label: "\\bigcup", glyph: "⋃" },
  { label: "\\bigsqcup", glyph: "⊔" },
  { label: "\\bigvee", glyph: "⋁" },
  { label: "\\bigwedge", glyph: "⋀" },
  { label: "\\bigodot", glyph: "⊙" },
  { label: "\\bigoplus", glyph: "⊕" },
  { label: "\\bigotimes", glyph: "⊗" },
  { label: "\\biguplus", glyph: "⊎" },
  { label: "\\sin" },
  { label: "\\cos" },
  { label: "\\tan" },
  { label: "\\cot" },
  { label: "\\sec" },
  { label: "\\csc" },
  { label: "\\arcsin" },
  { label: "\\arccos" },
  { label: "\\arctan" },
  { label: "\\sinh" },
  { label: "\\cosh" },
  { label: "\\tanh" },
  { label: "\\coth" },
  { label: "\\log" },
  { label: "\\ln" },
  { label: "\\exp" },
  { label: "\\lim" },
  { label: "\\liminf" },
  { label: "\\limsup" },
  { label: "\\min" },
  { label: "\\max" },
  { label: "\\sup" },
  { label: "\\inf" },
  { label: "\\dim" },
  { label: "\\deg" },
  { label: "\\det" },
  { label: "\\gcd" },
  { label: "\\hom" },
  { label: "\\ker" },
  { label: "\\arg" },
  { label: "\\Pr" },
  { label: "\\bmod" },
  { label: "\\pmod", template: "\\pmod{${}}${}" },
  { label: "\\operatorname", template: "\\operatorname{${}}${}" },
  { label: "\\DeclareMathOperator", template: "\\DeclareMathOperator{${}}{${}}${}" },
  { label: "\\injlim" },
  { label: "\\projlim" },
  { label: "\\varinjlim" },
  { label: "\\varprojlim" },
  { label: "\\varliminf" },
  { label: "\\varlimsup" },
  { label: "\\left" },
  { label: "\\right" },
  { label: "\\middle" },
  { label: "\\langle", glyph: "⟨" },
  { label: "\\rangle", glyph: "⟩" },
  { label: "\\lfloor", glyph: "⌊" },
  { label: "\\rfloor", glyph: "⌋" },
  { label: "\\lceil", glyph: "⌈" },
  { label: "\\rceil", glyph: "⌉" },
  { label: "\\lbrace", glyph: "{" },
  { label: "\\rbrace", glyph: "}" },
  { label: "\\vert", glyph: "|" },
  { label: "\\Vert", glyph: "‖" },
  { label: "\\backslash", glyph: "\\" },
  { label: "\\big" },
  { label: "\\Big" },
  { label: "\\bigg" },
  { label: "\\Bigg" },
  { label: "\\llcorner", glyph: "⌞" },
  { label: "\\lrcorner", glyph: "⌟" },
  { label: "\\ulcorner", glyph: "⌜" },
  { label: "\\urcorner", glyph: "⌝" },
  { label: "\\hat", template: "\\hat{${}}${}" },
  { label: "\\bar", template: "\\bar{${}}${}" },
  { label: "\\vec", template: "\\vec{${}}${}" },
  { label: "\\dot", template: "\\dot{${}}${}" },
  { label: "\\ddot", template: "\\ddot{${}}${}" },
  { label: "\\tilde", template: "\\tilde{${}}${}" },
  { label: "\\grave", template: "\\grave{${}}${}" },
  { label: "\\acute", template: "\\acute{${}}${}" },
  { label: "\\breve", template: "\\breve{${}}${}" },
  { label: "\\check", template: "\\check{${}}${}" },
  { label: "\\mathring", template: "\\mathring{${}}${}" },
  { label: "\\widehat", template: "\\widehat{${}}${}" },
  { label: "\\widetilde", template: "\\widetilde{${}}${}" },
  { label: "\\overrightarrow", template: "\\overrightarrow{${}}${}" },
  { label: "\\overleftarrow", template: "\\overleftarrow{${}}${}" },
  { label: "\\overleftrightarrow", template: "\\overleftrightarrow{${}}${}" },
  { label: "\\dddot", template: "\\dddot{${}}${}" },
  { label: "\\ddddot", template: "\\ddddot{${}}${}" },
  { label: "\\mathbb", template: "\\mathbb{${}}${}" },
  { label: "\\mathbf", template: "\\mathbf{${}}${}" },
  { label: "\\mathit", template: "\\mathit{${}}${}" },
  { label: "\\mathrm", template: "\\mathrm{${}}${}" },
  { label: "\\mathsf", template: "\\mathsf{${}}${}" },
  { label: "\\mathtt", template: "\\mathtt{${}}${}" },
  { label: "\\mathcal", template: "\\mathcal{${}}${}" },
  { label: "\\mathfrak", template: "\\mathfrak{${}}${}" },
  { label: "\\mathscr", template: "\\mathscr{${}}${}" },
  { label: "\\text", template: "\\text{${}}${}" },
  { label: "\\textbf", template: "\\textbf{${}}${}" },
  { label: "\\textit", template: "\\textit{${}}${}" },
  { label: "\\textrm", template: "\\textrm{${}}${}" },
  { label: "\\textsf", template: "\\textsf{${}}${}" },
  { label: "\\texttt", template: "\\texttt{${}}${}" },
  { label: "\\frac", template: "\\frac{${}}{${}}${}" },
  { label: "\\dfrac", template: "\\dfrac{${}}{${}}${}" },
  { label: "\\tfrac", template: "\\tfrac{${}}{${}}${}" },
  { label: "\\cfrac", template: "\\cfrac{${}}{${}}${}" },
  { label: "\\sqrt", template: "\\sqrt{${}}${}" },
  { label: "\\binom", template: "\\binom{${}}{${}}${}" },
  { label: "\\dbinom", template: "\\dbinom{${}}{${}}${}" },
  { label: "\\tbinom", template: "\\tbinom{${}}{${}}${}" },
  { label: "\\genfrac", template: "\\genfrac{${}}{${}}{${}}{${}}{${}}{${}}${}" },
  { label: "\\overline", template: "\\overline{${}}${}" },
  { label: "\\underline", template: "\\underline{${}}${}" },
  { label: "\\overbrace", template: "\\overbrace{${}}${}" },
  { label: "\\underbrace", template: "\\underbrace{${}}${}" },
  { label: "\\overset", template: "\\overset{${}}{${}}${}" },
  { label: "\\underset", template: "\\underset{${}}{${}}${}" },
  { label: "\\stackrel", template: "\\stackrel{${}}{${}}${}" },
  { label: "\\boxed", template: "\\boxed{${}}${}" },
  { label: "\\substack", template: "\\substack{${}}${}" },
  { label: "\\smash", template: "\\smash{${}}${}" },
  { label: "\\phantom", template: "\\phantom{${}}${}" },
  { label: "\\vphantom", template: "\\vphantom{${}}${}" },
  { label: "\\hphantom", template: "\\hphantom{${}}${}" },
  { label: "\\displaystyle" },
  { label: "\\textstyle" },
  { label: "\\limits" },
  { label: "\\nolimits" },
  { label: "\\not" },
  { label: "\\dots", glyph: "…" },
  { label: "\\ldots", glyph: "…" },
  { label: "\\cdots", glyph: "⋯" },
  { label: "\\vdots", glyph: "⋮" },
  { label: "\\ddots", glyph: "⋱" },
  { label: "\\infty", glyph: "∞" },
  { label: "\\partial", glyph: "∂" },
  { label: "\\nabla", glyph: "∇" },
  { label: "\\forall", glyph: "∀" },
  { label: "\\exists", glyph: "∃" },
  { label: "\\nexists", glyph: "∄" },
  { label: "\\emptyset", glyph: "∅" },
  { label: "\\varnothing", glyph: "∅" },
  { label: "\\aleph", glyph: "ℵ" },
  { label: "\\beth", glyph: "ℶ" },
  { label: "\\gimel", glyph: "ℷ" },
  { label: "\\daleth", glyph: "ℸ" },
  { label: "\\hbar", glyph: "ℏ" },
  { label: "\\hslash", glyph: "ℏ" },
  { label: "\\ell", glyph: "ℓ" },
  { label: "\\Re", glyph: "ℜ" },
  { label: "\\Im", glyph: "ℑ" },
  { label: "\\angle", glyph: "∠" },
  { label: "\\measuredangle", glyph: "∡" },
  { label: "\\sphericalangle", glyph: "∢" },
  { label: "\\prime", glyph: "′" },
  { label: "\\backprime", glyph: "‵" },
  { label: "\\top", glyph: "⊤" },
  { label: "\\bot", glyph: "⊥" },
  { label: "\\neg", glyph: "¬" },
  { label: "\\dagger", glyph: "†" },
  { label: "\\ddagger", glyph: "‡" },
  { label: "\\sharp", glyph: "♯" },
  { label: "\\flat", glyph: "♭" },
  { label: "\\natural", glyph: "♮" },
  { label: "\\surd", glyph: "√" },
  { label: "\\complement", glyph: "∁" },
  { label: "\\eth", glyph: "ð" },
  { label: "\\square", glyph: "□" },
  { label: "\\blacksquare", glyph: "■" },
  { label: "\\lozenge", glyph: "◊" },
  { label: "\\blacklozenge", glyph: "◆" },
  { label: "\\triangle", glyph: "△" },
  { label: "\\blacktriangle", glyph: "▲" },
  { label: "\\bigstar", glyph: "★" },
  { label: "\\checkmark", glyph: "✓" },
  { label: "\\circledR", glyph: "®" },
  { label: "\\circledS", glyph: "Ⓢ" },
  { label: "\\mho", glyph: "℧" },
  { label: "\\eqref", template: "\\eqref{${}}${}" },
  { label: "\\tag", template: "\\tag{${}}${}" },
  { label: "\\newcommand", template: "\\newcommand{${}}{${}}${}" },
  { label: "\\renewcommand", template: "\\renewcommand{${}}{${}}${}" },
  { label: "\\newenvironment", template: "\\newenvironment{${}}{${}}{${}}${}" },
  { label: "\\renewenvironment", template: "\\renewenvironment{${}}{${}}{${}}${}" },
  { label: "\\def" },
  { label: "\\let" },
  { label: "\\begin{matrix}", template: "\\begin{matrix}\n\t${}\n\\end{matrix}${}" },
  { label: "\\begin{pmatrix}", template: "\\begin{pmatrix}\n\t${}\n\\end{pmatrix}${}" },
  { label: "\\begin{bmatrix}", template: "\\begin{bmatrix}\n\t${}\n\\end{bmatrix}${}" },
  { label: "\\begin{Bmatrix}", template: "\\begin{Bmatrix}\n\t${}\n\\end{Bmatrix}${}" },
  { label: "\\begin{vmatrix}", template: "\\begin{vmatrix}\n\t${}\n\\end{vmatrix}${}" },
  { label: "\\begin{Vmatrix}", template: "\\begin{Vmatrix}\n\t${}\n\\end{Vmatrix}${}" },
  { label: "\\begin{smallmatrix}", template: "\\begin{smallmatrix}\n\t${}\n\\end{smallmatrix}${}" },
  { label: "\\begin{cases}", template: "\\begin{cases}\n\t${}\n\\end{cases}${}" },
  { label: "\\begin{aligned}", template: "\\begin{aligned}\n\t${}\n\\end{aligned}${}" },
  { label: "\\begin{align}", template: "\\begin{align}\n\t${}\n\\end{align}${}" },
  { label: "\\begin{align*}", template: "\\begin{align*}\n\t${}\n\\end{align*}${}" },
  { label: "\\begin{alignat}", template: "\\begin{alignat}{${}}\n\t${}\n\\end{alignat}${}" },
  { label: "\\begin{alignat*}", template: "\\begin{alignat*}{${}}\n\t${}\n\\end{alignat*}${}" },
  { label: "\\begin{gathered}", template: "\\begin{gathered}\n\t${}\n\\end{gathered}${}" },
  { label: "\\begin{gather}", template: "\\begin{gather}\n\t${}\n\\end{gather}${}" },
  { label: "\\begin{gather*}", template: "\\begin{gather*}\n\t${}\n\\end{gather*}${}" },
  { label: "\\begin{split}", template: "\\begin{split}\n\t${}\n\\end{split}${}" },
  { label: "\\begin{multline}", template: "\\begin{multline}\n\t${}\n\\end{multline}${}" },
  { label: "\\begin{multline*}", template: "\\begin{multline*}\n\t${}\n\\end{multline*}${}" },
  { label: "\\begin{equation}", template: "\\begin{equation}\n\t${}\n\\end{equation}${}" },
  { label: "\\begin{equation*}", template: "\\begin{equation*}\n\t${}\n\\end{equation*}${}" },
  { label: "\\begin{array}", template: "\\begin{array}{${}}\n\t${}\n\\end{array}${}" },
  { label: "\\begin{subarray}", template: "\\begin{subarray}{${}}\n\t${}\n\\end{subarray}${}" },
];
