// Shared clause grammar for the spec generators (gen-spec-matrix.mjs,
// gen-smoke-list.mjs). Format contract: docs/spec/README.md §2, §4, §5.
// Dependency-free (node:fs / node:path only). ESM.

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = join(fileURLToPath(import.meta.url), '..', '..');
export const SPEC_DIR = join(ROOT, 'docs', 'spec');
export const SMOKE_PATH = join(SPEC_DIR, '_manual-smoke.md');

export const ID_RE = /\b[A-Z][A-Z0-9]*-[A-Z]+-\d+\b/g;
// - **ID** `[tag]` `[tag]` — statement
export const CLAUSE_RE = /^\s*-\s+\*\*([A-Z][A-Z0-9]*-[A-Z]+-\d+)\*\*((?:\s*`\[[^\]]+\]`)*)\s+—\s+(.+?)\s*$/;
const CLAUSE_START_RE = /^\s*-\s+\*\*[A-Z][A-Z0-9]*-[A-Z]+-\d+\*\*/;
const TAG_RE = /`\[([^\]]+)\]`/g;

export function walk(dir, test, out) {
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name === 'dist' || name.startsWith('.')) continue;
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, test, out);
    else if (test(p)) out.push(p);
  }
}

// Every declared clause across the normative spec files (generated `_*.md`
// and README excluded), plus the duplicate IDs and malformed clause lines
// spec:check reports.
export function load_clauses() {
  const clauses = new Map(); // id -> { id, file, statement, tags:Set, line }
  const duplicates = [];
  const malformed = []; // { file, line, text }
  const specFiles = [];
  walk(SPEC_DIR, (p) => p.endsWith('.md') && !basename(p).startsWith('_') && basename(p) !== 'README.md', specFiles);
  specFiles.sort();

  for (const file of specFiles) {
    const rel = relative(ROOT, file);
    readFileSync(file, 'utf8').split('\n').forEach((text, i) => {
      // A line that starts a bold-ID clause but fails the strict shape is malformed.
      if (!CLAUSE_START_RE.test(text)) return;
      const m = CLAUSE_RE.exec(text);
      if (!m) {
        malformed.push({ file: rel, line: i + 1, text: text.trim() });
        return;
      }
      const [, id, tagRegion, statement] = m;
      const tags = new Set();
      let tm;
      TAG_RE.lastIndex = 0;
      while ((tm = TAG_RE.exec(tagRegion))) tags.add(tm[1]);
      if (clauses.has(id)) duplicates.push({ id, a: clauses.get(id).file, b: rel });
      else clauses.set(id, { id, file: rel, statement, tags, line: i + 1 });
    });
  }
  return { clauses, duplicates, malformed, specFiles };
}

// Conformance follows the first `inherits:` target; `seen` stops an
// `inherits:` cycle from recursing forever.
export function conformance(clauses, c, seen = new Set()) {
  if (c.tags.has('divergent')) return 'divergent';
  if (c.tags.has('unknown')) return 'unknown';
  seen.add(c.id);
  for (const t of c.tags) {
    if (t.startsWith('inherits:')) {
      const target = clauses.get(t.slice('inherits:'.length));
      if (target && !seen.has(target.id)) return conformance(clauses, target, seen);
    }
  }
  if (c.tags.has('accepted')) return 'accepted';
  return 'conforming';
}

// Smoke coverage: an own [smoke] tag or an inherited [smoke] clause.
export function has_smoke(clauses, id, seen = new Set()) {
  if (seen.has(id)) return false;
  seen.add(id);
  const c = clauses.get(id);
  if (!c) return false;
  if (c.tags.has('smoke')) return true;
  for (const t of c.tags) {
    if (t.startsWith('inherits:') && has_smoke(clauses, t.slice('inherits:'.length), seen)) return true;
  }
  return false;
}

export function render_smoke_list(clauses) {
  const smoke = [...clauses.values()]
    .filter((c) => has_smoke(clauses, c.id))
    .sort((a, b) => a.id.localeCompare(b.id, undefined, { numeric: true }));

  const byFile = new Map();
  for (const c of smoke) {
    if (!byFile.has(c.file)) byFile.set(c.file, []);
    byFile.get(c.file).push(c);
  }

  let out = '';
  out += '# Manual-Smoke List\n\n';
  out += '> GENERATED by `pnpm run spec:smoke` — do not hand-edit.\n';
  out += `> ${smoke.length} clauses require manual verification in a real VS Code webview.\n\n`;
  out += 'Each clause below carries `[smoke]` coverage (no headless test fully pins it).\n';
  out += 'Verify under F5 in the Extension Development Host (Desktop) and vscode.dev (Web).\n';
  out += 'A `conformance` other than `conforming` means the clause also awaits a ruling\n';
  out += '(`unknown` → confirm by smoke; cross-referenced in `_decision-points.md`).\n\n';

  for (const [file, cs] of [...byFile.entries()].sort()) {
    out += `## \`${file}\`\n\n`;
    out += '| Clause | Conformance | Behavior to verify |\n|---|---|---|\n';
    for (const c of cs) {
      const stmt = c.statement.replace(/\|/g, '\\|');
      out += `| ${c.id} | ${conformance(clauses, c)} | ${stmt} |\n`;
    }
    out += '\n';
  }
  return { text: out, count: smoke.length, files: byFile.size };
}
